:robot: I have created a release *beep* *boop*
---


<details><summary>google-ai-generativelanguage: 0.5.3</summary>

## [0.5.3](https://github.com/googleapis/google-cloud-python/compare/google-ai-generativelanguage-v0.5.2...google-ai-generativelanguage-v0.5.3) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-analytics-admin: 0.22.6</summary>

## [0.22.6](https://github.com/googleapis/google-cloud-python/compare/google-analytics-admin-v0.22.5...google-analytics-admin-v0.22.6) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-analytics-data: 0.18.6</summary>

## [0.18.6](https://github.com/googleapis/google-cloud-python/compare/google-analytics-data-v0.18.5...google-analytics-data-v0.18.6) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-apps-meet: 0.1.5</summary>

## [0.1.5](https://github.com/googleapis/google-cloud-python/compare/google-apps-meet-v0.1.4...google-apps-meet-v0.1.5) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-apps-script-type: 0.3.7</summary>

## [0.3.7](https://github.com/googleapis/google-cloud-python/compare/google-apps-script-type-v0.3.6...google-apps-script-type-v0.3.7) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-area120-tables: 0.11.8</summary>

## [0.11.8](https://github.com/googleapis/google-cloud-python/compare/google-area120-tables-v0.11.7...google-area120-tables-v0.11.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-access-approval: 1.13.2</summary>

## [1.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-access-approval-v1.13.1...google-cloud-access-approval-v1.13.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-advisorynotifications: 0.3.6</summary>

## [0.3.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-advisorynotifications-v0.3.5...google-cloud-advisorynotifications-v0.3.6) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-alloydb: 0.3.9</summary>

## [0.3.9](https://github.com/googleapis/google-cloud-python/compare/google-cloud-alloydb-v0.3.8...google-cloud-alloydb-v0.3.9) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-alloydb-connectors: 0.1.3</summary>

## [0.1.3](https://github.com/googleapis/google-cloud-python/compare/google-cloud-alloydb-connectors-v0.1.2...google-cloud-alloydb-connectors-v0.1.3) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-api-gateway: 1.9.2</summary>

## [1.9.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-api-gateway-v1.9.1...google-cloud-api-gateway-v1.9.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-api-keys: 0.5.8</summary>

## [0.5.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-api-keys-v0.5.7...google-cloud-api-keys-v0.5.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-apigee-connect: 1.9.2</summary>

## [1.9.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-apigee-connect-v1.9.1...google-cloud-apigee-connect-v1.9.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-apigee-registry: 0.6.8</summary>

## [0.6.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-apigee-registry-v0.6.7...google-cloud-apigee-registry-v0.6.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-appengine-admin: 1.11.2</summary>

## [1.11.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-appengine-admin-v1.11.1...google-cloud-appengine-admin-v1.11.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-appengine-logging: 1.4.2</summary>

## [1.4.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-appengine-logging-v1.4.1...google-cloud-appengine-logging-v1.4.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-artifact-registry: 1.11.2</summary>

## [1.11.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-artifact-registry-v1.11.1...google-cloud-artifact-registry-v1.11.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-asset: 3.24.2</summary>

## [3.24.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-asset-v3.24.1...google-cloud-asset-v3.24.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
* fix ValueError in test__validate_universe_domain ([e6cd222](https://github.com/googleapis/google-cloud-python/commit/e6cd22212a6f62907c855cf889ee6055c1969eb0))


### Documentation

* [google-cloud-asset] updated comments ([e6cd222](https://github.com/googleapis/google-cloud-python/commit/e6cd22212a6f62907c855cf889ee6055c1969eb0))
</details>

<details><summary>google-cloud-assured-workloads: 1.12.2</summary>

## [1.12.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-assured-workloads-v1.12.1...google-cloud-assured-workloads-v1.12.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-automl: 2.13.2</summary>

## [2.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-automl-v2.13.1...google-cloud-automl-v2.13.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12303](https://github.com/googleapis/google-cloud-python/issues/12303)) ([fbb80c3](https://github.com/googleapis/google-cloud-python/commit/fbb80c32f7db91e25bd1cc30966f630728ff6d6a))
</details>

<details><summary>google-cloud-bare-metal-solution: 1.7.2</summary>

## [1.7.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-bare-metal-solution-v1.7.1...google-cloud-bare-metal-solution-v1.7.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-batch: 0.17.12</summary>

## [0.17.12](https://github.com/googleapis/google-cloud-python/compare/google-cloud-batch-v0.17.11...google-cloud-batch-v0.17.12) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12280](https://github.com/googleapis/google-cloud-python/issues/12280)) ([2d75d0e](https://github.com/googleapis/google-cloud-python/commit/2d75d0e67ca4cccddc688bd37c14ac80564a2e65))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-beyondcorp-appconnections: 0.4.8</summary>

## [0.4.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-beyondcorp-appconnections-v0.4.7...google-cloud-beyondcorp-appconnections-v0.4.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-beyondcorp-appconnectors: 0.4.8</summary>

## [0.4.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-beyondcorp-appconnectors-v0.4.7...google-cloud-beyondcorp-appconnectors-v0.4.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-beyondcorp-appgateways: 0.4.8</summary>

## [0.4.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-beyondcorp-appgateways-v0.4.7...google-cloud-beyondcorp-appgateways-v0.4.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-beyondcorp-clientconnectorservices: 0.4.8</summary>

## [0.4.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-beyondcorp-clientconnectorservices-v0.4.7...google-cloud-beyondcorp-clientconnectorservices-v0.4.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-beyondcorp-clientgateways: 0.4.7</summary>

## [0.4.7](https://github.com/googleapis/google-cloud-python/compare/google-cloud-beyondcorp-clientgateways-v0.4.6...google-cloud-beyondcorp-clientgateways-v0.4.7) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-bigquery-analyticshub: 0.4.7</summary>

## [0.4.7](https://github.com/googleapis/google-cloud-python/compare/google-cloud-bigquery-analyticshub-v0.4.6...google-cloud-bigquery-analyticshub-v0.4.7) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-bigquery-biglake: 0.4.6</summary>

## [0.4.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-bigquery-biglake-v0.4.5...google-cloud-bigquery-biglake-v0.4.6) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-bigquery-connection: 1.15.2</summary>

## [1.15.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-bigquery-connection-v1.15.1...google-cloud-bigquery-connection-v1.15.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-bigquery-data-exchange: 0.5.10</summary>

## [0.5.10](https://github.com/googleapis/google-cloud-python/compare/google-cloud-bigquery-data-exchange-v0.5.9...google-cloud-bigquery-data-exchange-v0.5.10) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-bigquery-datapolicies: 0.6.5</summary>

## [0.6.5](https://github.com/googleapis/google-cloud-python/compare/google-cloud-bigquery-datapolicies-v0.6.4...google-cloud-bigquery-datapolicies-v0.6.5) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-bigquery-datatransfer: 3.15.0</summary>

## [3.15.0](https://github.com/googleapis/google-cloud-python/compare/google-cloud-bigquery-datatransfer-v3.14.1...google-cloud-bigquery-datatransfer-v3.15.0) (2024-02-15)


### Features

* [google-cloud-bigquery-datatransfer] Add UnenrollDataSources API which gives users a programmatic way to unenroll data sources ([#12296](https://github.com/googleapis/google-cloud-python/issues/12296)) ([dd9c9fc](https://github.com/googleapis/google-cloud-python/commit/dd9c9fcfbc8aacfa659d52b8e81ded1d3bf5d8b0))


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-bigquery-logging: 1.4.2</summary>

## [1.4.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-bigquery-logging-v1.4.1...google-cloud-bigquery-logging-v1.4.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-bigquery-migration: 0.11.6</summary>

## [0.11.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-bigquery-migration-v0.11.5...google-cloud-bigquery-migration-v0.11.6) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-bigquery-reservation: 1.13.2</summary>

## [1.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-bigquery-reservation-v1.13.1...google-cloud-bigquery-reservation-v1.13.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-billing: 1.13.2</summary>

## [1.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-billing-v1.13.1...google-cloud-billing-v1.13.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))


### Documentation

* [google-cloud-billing] Clarify that the parent field in the CreateBillingAccountRequest must be a billing account ([#12299](https://github.com/googleapis/google-cloud-python/issues/12299)) ([1ff477c](https://github.com/googleapis/google-cloud-python/commit/1ff477c9b959f1fc4b3b0e46721141702a47aff2))
</details>

<details><summary>google-cloud-billing-budgets: 1.14.2</summary>

## [1.14.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-billing-budgets-v1.14.1...google-cloud-billing-budgets-v1.14.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-binary-authorization: 1.10.2</summary>

## [1.10.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-binary-authorization-v1.10.1...google-cloud-binary-authorization-v1.10.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
</details>

<details><summary>google-cloud-build: 3.23.2</summary>

## [3.23.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-build-v3.23.1...google-cloud-build-v3.23.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12304](https://github.com/googleapis/google-cloud-python/issues/12304)) ([c52e0cd](https://github.com/googleapis/google-cloud-python/commit/c52e0cdbddf44c96f642d8d596c5413c4006ba82))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-certificate-manager: 1.6.2</summary>

## [1.6.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-certificate-manager-v1.6.1...google-cloud-certificate-manager-v1.6.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-channel: 1.18.2</summary>

## [1.18.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-channel-v1.18.1...google-cloud-channel-v1.18.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-cloudquotas: 0.1.3</summary>

## [0.1.3](https://github.com/googleapis/google-cloud-python/compare/google-cloud-cloudquotas-v0.1.2...google-cloud-cloudquotas-v0.1.3) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12281](https://github.com/googleapis/google-cloud-python/issues/12281)) ([62cf934](https://github.com/googleapis/google-cloud-python/commit/62cf934b140173d7b39e6c9ffa66e218b98260d4))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-commerce-consumer-procurement: 0.1.4</summary>

## [0.1.4](https://github.com/googleapis/google-cloud-python/compare/google-cloud-commerce-consumer-procurement-v0.1.3...google-cloud-commerce-consumer-procurement-v0.1.4) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-common: 1.3.2</summary>

## [1.3.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-common-v1.3.1...google-cloud-common-v1.3.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-compute: 1.17.0</summary>

## [1.17.0](https://github.com/googleapis/google-cloud-python/compare/google-cloud-compute-v1.16.1...google-cloud-compute-v1.17.0) (2024-02-15)


### Features

* Update Compute Engine API to revision 20240130 ([#881](https://github.com/googleapis/google-cloud-python/issues/881)) ([#12292](https://github.com/googleapis/google-cloud-python/issues/12292)) ([3f0e861](https://github.com/googleapis/google-cloud-python/commit/3f0e86105b994d3f5f5212c62a39aea2be7989cc))


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-confidentialcomputing: 0.4.6</summary>

## [0.4.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-confidentialcomputing-v0.4.5...google-cloud-confidentialcomputing-v0.4.6) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-config: 0.1.6</summary>

## [0.1.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-config-v0.1.5...google-cloud-config-v0.1.6) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-contact-center-insights: 1.17.2</summary>

## [1.17.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-contact-center-insights-v1.17.1...google-cloud-contact-center-insights-v1.17.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-container: 2.41.0</summary>

## [2.41.0](https://github.com/googleapis/google-cloud-python/compare/google-cloud-container-v2.40.0...google-cloud-container-v2.41.0) (2024-02-15)


### Features

* [google-cloud-container] added configuration for the StatefulHA addon to the AddonsConfig ([38daeac](https://github.com/googleapis/google-cloud-python/commit/38daeace2bf4a8fdf6662799b7350b516013aff4))


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
* fix ValueError in test__validate_universe_domain ([38daeac](https://github.com/googleapis/google-cloud-python/commit/38daeace2bf4a8fdf6662799b7350b516013aff4))
</details>

<details><summary>google-cloud-containeranalysis: 2.14.2</summary>

## [2.14.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-containeranalysis-v2.14.1...google-cloud-containeranalysis-v2.14.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-contentwarehouse: 0.7.6</summary>

## [0.7.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-contentwarehouse-v0.7.5...google-cloud-contentwarehouse-v0.7.6) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-data-fusion: 1.10.2</summary>

## [1.10.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-data-fusion-v1.10.1...google-cloud-data-fusion-v1.10.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-data-qna: 0.10.8</summary>

## [0.10.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-data-qna-v0.10.7...google-cloud-data-qna-v0.10.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-datacatalog: 3.18.2</summary>

## [3.18.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-datacatalog-v3.18.1...google-cloud-datacatalog-v3.18.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-datacatalog-lineage: 0.3.5</summary>

## [0.3.5](https://github.com/googleapis/google-cloud-python/compare/google-cloud-datacatalog-lineage-v0.3.4...google-cloud-datacatalog-lineage-v0.3.5) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-dataflow-client: 0.8.9</summary>

## [0.8.9](https://github.com/googleapis/google-cloud-python/compare/google-cloud-dataflow-client-v0.8.8...google-cloud-dataflow-client-v0.8.9) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-dataform: 0.5.8</summary>

## [0.5.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-dataform-v0.5.7...google-cloud-dataform-v0.5.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-datalabeling: 1.10.2</summary>

## [1.10.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-datalabeling-v1.10.1...google-cloud-datalabeling-v1.10.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-dataplex: 1.12.2</summary>

## [1.12.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-dataplex-v1.12.1...google-cloud-dataplex-v1.12.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12305](https://github.com/googleapis/google-cloud-python/issues/12305)) ([2aa7f17](https://github.com/googleapis/google-cloud-python/commit/2aa7f17a5fd4f2249260225db91fb0414d06eaa7))
</details>

<details><summary>google-cloud-dataproc: 5.9.2</summary>

## [5.9.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-dataproc-v5.9.1...google-cloud-dataproc-v5.9.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-dataproc-metastore: 1.15.2</summary>

## [1.15.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-dataproc-metastore-v1.15.1...google-cloud-dataproc-metastore-v1.15.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-datastream: 1.9.2</summary>

## [1.9.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-datastream-v1.9.1...google-cloud-datastream-v1.9.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-deploy: 1.17.2</summary>

## [1.17.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-deploy-v1.17.1...google-cloud-deploy-v1.17.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-dialogflow: 2.28.2</summary>

## [2.28.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-dialogflow-v2.28.1...google-cloud-dialogflow-v2.28.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-dialogflow-cx: 1.32.0</summary>

## [1.32.0](https://github.com/googleapis/google-cloud-python/compare/google-cloud-dialogflow-cx-v1.31.1...google-cloud-dialogflow-cx-v1.32.0) (2024-02-15)


### Features

* A new field `current_flow` is added to message `.google.cloud.dialogflow.cx.v3.QueryResult` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new field `description` is added to message `.google.cloud.dialogflow.cx.v3.Page` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new field `disable_data_store_fallback` is added to message `.google.cloud.dialogflow.cx.v3.GenerativeSettings` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new field `language_code` is added to message `Changelog` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new field `opt_out_conformer_model_migration` is added to message `InputAudioConfig` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new field `webhook_display_names` is added to message `.google.cloud.dialogflow.cx.v3.QueryResult` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new field `webhook_ids` is added to message `.google.cloud.dialogflow.cx.v3.QueryResult` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new field `webhook_latencies` is added to message `.google.cloud.dialogflow.cx.v3.QueryResult` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new field `webhook_tags` is added to message `.google.cloud.dialogflow.cx.v3.QueryResult` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new message `ExportEntityTypesMetadata` is added ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new message `ExportEntityTypesRequest` is added ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new message `ExportEntityTypesResponse` is added ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new message `ImportEntityTypesMetadata` is added ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new message `ImportEntityTypesRequest` is added ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new message `ImportEntityTypesResponse` is added ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new method `ExportEntityTypes` is added to service `EntityTypes` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new method `ImportEntityTypes` is added to service `EntityTypes` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A new method `ServerStreamingDetectIntent` is added to service `Sessions` ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* Public preview the  Dialogflow LLM based agent ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
* Require google-api-core&gt;=1.34.1 ([#12313](https://github.com/googleapis/google-cloud-python/issues/12313)) ([b099445](https://github.com/googleapis/google-cloud-python/commit/b0994458dd4c7d8a7e7d93ebce10b4b08e811bf5))


### Documentation

* A comment for enum value `END_OF_SINGLE_UTTERANCE` in enum `MessageType` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for enum value `END_OF_SINGLE_UTTERANCE` in enum `MessageType` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for enum value `USE_BEST_AVAILABLE` in enum `SpeechModelVariant` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for enum value `USE_BEST_AVAILABLE` in enum `SpeechModelVariant` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for enum value `USE_ENHANCED` in enum `SpeechModelVariant` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for enum value `USE_ENHANCED` in enum `SpeechModelVariant` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for field `model` in message `.google.cloud.dialogflow.cx.v3.InputAudioConfig` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for field `model` in message `.google.cloud.dialogflow.cx.v3beta1.InputAudioConfig` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for field `session_ttl` in message `.google.cloud.dialogflow.cx.v3.QueryParameters` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for field `session_ttl` in message `.google.cloud.dialogflow.cx.v3beta1.QueryParameters` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for field `start_flow` in message `.google.cloud.dialogflow.cx.v3.Agent` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for field `start_flow` in message `.google.cloud.dialogflow.cx.v3beta1.Agent` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for field `text` in message `.google.cloud.dialogflow.cx.v3.TextInput` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for field `text` in message `.google.cloud.dialogflow.cx.v3beta1.TextInput` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for message `QueryInput` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
* A comment for message `QueryInput` is changed ([e1dbb80](https://github.com/googleapis/google-cloud-python/commit/e1dbb8098ca8d4f8b19695c1b2b11e06e7c84e01))
</details>

<details><summary>google-cloud-discoveryengine: 0.11.8</summary>

## [0.11.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-discoveryengine-v0.11.7...google-cloud-discoveryengine-v0.11.8) (2024-02-15)


### Features

* Add data store, engine, serving config and site search engine services  ([00cf69e](https://github.com/googleapis/google-cloud-python/commit/00cf69ee2536bda6a2ccc086343d4be2744e7303))
* Add engine support for multi-turn search and search APIs ([00cf69e](https://github.com/googleapis/google-cloud-python/commit/00cf69ee2536bda6a2ccc086343d4be2744e7303))
* Add suggestion deny list import/purge APIs ([00cf69e](https://github.com/googleapis/google-cloud-python/commit/00cf69ee2536bda6a2ccc086343d4be2744e7303))
* Support search summarization with citations and references ([00cf69e](https://github.com/googleapis/google-cloud-python/commit/00cf69ee2536bda6a2ccc086343d4be2744e7303))


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))


### Documentation

* Keep the API doc up-to-date with recent changes ([00cf69e](https://github.com/googleapis/google-cloud-python/commit/00cf69ee2536bda6a2ccc086343d4be2744e7303))
</details>

<details><summary>google-cloud-dlp: 3.15.2</summary>

## [3.15.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-dlp-v3.15.1...google-cloud-dlp-v3.15.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-dms: 1.9.2</summary>

## [1.9.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-dms-v1.9.1...google-cloud-dms-v1.9.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12282](https://github.com/googleapis/google-cloud-python/issues/12282)) ([b985096](https://github.com/googleapis/google-cloud-python/commit/b985096d43add8214172ff993e00293e6c8757cb))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-documentai: 2.24.0</summary>

## [2.24.0](https://github.com/googleapis/google-cloud-python/compare/google-cloud-documentai-v2.23.0...google-cloud-documentai-v2.24.0) (2024-02-15)


### Features

* A new field `display_name` is added to message `DocumentSchema` ([38dde99](https://github.com/googleapis/google-cloud-python/commit/38dde996c05fe751643ff92ceb5aed7dc6e0e315))
* A new field `display_name` is added to message `DocumentSchema` ([aae7bf5](https://github.com/googleapis/google-cloud-python/commit/aae7bf53622e4fd56fdc767d327a5d5f978718f4))
* A new field `labels` is added to messages `ProcessRequest` and `BatchProcessRequest` ([38dde99](https://github.com/googleapis/google-cloud-python/commit/38dde996c05fe751643ff92ceb5aed7dc6e0e315))
* A new field `labels` is added to messages `ProcessRequest` and `BatchProcessRequest` ([aae7bf5](https://github.com/googleapis/google-cloud-python/commit/aae7bf53622e4fd56fdc767d327a5d5f978718f4))
* A new field `schema_override` is added to message `ProcessOptions` ([aae7bf5](https://github.com/googleapis/google-cloud-python/commit/aae7bf53622e4fd56fdc767d327a5d5f978718f4))
* A new field foundation_model_tuning_options is added to message TrainProcessorVersionRequest ([38dde99](https://github.com/googleapis/google-cloud-python/commit/38dde996c05fe751643ff92ceb5aed7dc6e0e315))
* A new message FoundationModelTuningOptions is added ([38dde99](https://github.com/googleapis/google-cloud-python/commit/38dde996c05fe751643ff92ceb5aed7dc6e0e315))


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* deprecate `Dataset.document_warehouse_config` ([38dde99](https://github.com/googleapis/google-cloud-python/commit/38dde996c05fe751643ff92ceb5aed7dc6e0e315))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))


### Documentation

* updated comments ([38dde99](https://github.com/googleapis/google-cloud-python/commit/38dde996c05fe751643ff92ceb5aed7dc6e0e315))
* updated comments ([aae7bf5](https://github.com/googleapis/google-cloud-python/commit/aae7bf53622e4fd56fdc767d327a5d5f978718f4))
</details>

<details><summary>google-cloud-domains: 1.7.2</summary>

## [1.7.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-domains-v1.7.1...google-cloud-domains-v1.7.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-edgecontainer: 0.5.7</summary>

## [0.5.7](https://github.com/googleapis/google-cloud-python/compare/google-cloud-edgecontainer-v0.5.6...google-cloud-edgecontainer-v0.5.7) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-edgenetwork: 0.1.5</summary>

## [0.1.5](https://github.com/googleapis/google-cloud-python/compare/google-cloud-edgenetwork-v0.1.4...google-cloud-edgenetwork-v0.1.5) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-enterpriseknowledgegraph: 0.3.8</summary>

## [0.3.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-enterpriseknowledgegraph-v0.3.7...google-cloud-enterpriseknowledgegraph-v0.3.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-essential-contacts: 1.7.2</summary>

## [1.7.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-essential-contacts-v1.7.1...google-cloud-essential-contacts-v1.7.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-eventarc: 1.11.2</summary>

## [1.11.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-eventarc-v1.11.1...google-cloud-eventarc-v1.11.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-eventarc-publishing: 0.6.8</summary>

## [0.6.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-eventarc-publishing-v0.6.7...google-cloud-eventarc-publishing-v0.6.8) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-filestore: 1.9.2</summary>

## [1.9.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-filestore-v1.9.1...google-cloud-filestore-v1.9.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-functions: 1.16.2</summary>

## [1.16.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-functions-v1.16.1...google-cloud-functions-v1.16.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
</details>

<details><summary>google-cloud-gke-backup: 0.5.6</summary>

## [0.5.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-gke-backup-v0.5.5...google-cloud-gke-backup-v0.5.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12306](https://github.com/googleapis/google-cloud-python/issues/12306)) ([1e787f2](https://github.com/googleapis/google-cloud-python/commit/1e787f2079ac41ce634c7b90f02a6597cecb64be))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-gke-connect-gateway: 0.8.8</summary>

## [0.8.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-gke-connect-gateway-v0.8.7...google-cloud-gke-connect-gateway-v0.8.8) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-gke-hub: 1.12.2</summary>

## [1.12.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-gke-hub-v1.12.1...google-cloud-gke-hub-v1.12.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-gke-multicloud: 0.6.8</summary>

## [0.6.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-gke-multicloud-v0.6.7...google-cloud-gke-multicloud-v0.6.8) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-gsuiteaddons: 0.3.7</summary>

## [0.3.7](https://github.com/googleapis/google-cloud-python/compare/google-cloud-gsuiteaddons-v0.3.6...google-cloud-gsuiteaddons-v0.3.7) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-iam: 2.14.2</summary>

## [2.14.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-iam-v2.14.1...google-cloud-iam-v2.14.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-iam-logging: 1.3.2</summary>

## [1.3.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-iam-logging-v1.3.1...google-cloud-iam-logging-v1.3.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
</details>

<details><summary>google-cloud-iap: 1.13.2</summary>

## [1.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-iap-v1.13.1...google-cloud-iap-v1.13.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-ids: 1.7.2</summary>

## [1.7.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-ids-v1.7.1...google-cloud-ids-v1.7.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-kms: 2.21.2</summary>

## [2.21.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-kms-v2.21.1...google-cloud-kms-v2.21.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-kms-inventory: 0.2.5</summary>

## [0.2.5](https://github.com/googleapis/google-cloud-python/compare/google-cloud-kms-inventory-v0.2.4...google-cloud-kms-inventory-v0.2.5) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-language: 2.13.2</summary>

## [2.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-language-v2.13.1...google-cloud-language-v2.13.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([dd749df](https://github.com/googleapis/google-cloud-python/commit/dd749dfb4caf2e33f1152dfd8c4b0ac5424c381c))
</details>

<details><summary>google-cloud-life-sciences: 0.9.8</summary>

## [0.9.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-life-sciences-v0.9.7...google-cloud-life-sciences-v0.9.8) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-managed-identities: 1.9.2</summary>

## [1.9.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-managed-identities-v1.9.1...google-cloud-managed-identities-v1.9.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-media-translation: 0.11.8</summary>

## [0.11.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-media-translation-v0.11.7...google-cloud-media-translation-v0.11.8) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-memcache: 1.9.2</summary>

## [1.9.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-memcache-v1.9.1...google-cloud-memcache-v1.9.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-migrationcenter: 0.1.6</summary>

## [0.1.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-migrationcenter-v0.1.5...google-cloud-migrationcenter-v0.1.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-monitoring: 2.19.2</summary>

## [2.19.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-monitoring-v2.19.1...google-cloud-monitoring-v2.19.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
* make google-cloud-monitoring tests work without `mock` ([#12317](https://github.com/googleapis/google-cloud-python/issues/12317)) ([1988e0d](https://github.com/googleapis/google-cloud-python/commit/1988e0d753f4b15d6fadb310fb342ece0d7b0edd))
</details>

<details><summary>google-cloud-monitoring-dashboards: 2.15.0</summary>

## [2.15.0](https://github.com/googleapis/google-cloud-python/compare/google-cloud-monitoring-dashboards-v2.14.1...google-cloud-monitoring-dashboards-v2.15.0) (2024-02-15)


### Features

* [google-cloud-monitoring-dashboards] Add support for pie charts, incident lists, dropdown groups, error reporting panels, section headers, and styling options on text widgets ([#12295](https://github.com/googleapis/google-cloud-python/issues/12295)) ([95825ee](https://github.com/googleapis/google-cloud-python/commit/95825ee48e4f00ae0bcd385ca0822f7e4e86b90e))


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-monitoring-metrics-scopes: 1.6.2</summary>

## [1.6.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-monitoring-metrics-scopes-v1.6.1...google-cloud-monitoring-metrics-scopes-v1.6.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-netapp: 0.3.6</summary>

## [0.3.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-netapp-v0.3.5...google-cloud-netapp-v0.3.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12307](https://github.com/googleapis/google-cloud-python/issues/12307)) ([be87bc4](https://github.com/googleapis/google-cloud-python/commit/be87bc4a33fe32a512448a42246c9873da88269f))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-network-connectivity: 2.4.2</summary>

## [2.4.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-network-connectivity-v2.4.1...google-cloud-network-connectivity-v2.4.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-network-management: 1.13.2</summary>

## [1.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-network-management-v1.13.1...google-cloud-network-management-v1.13.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-network-security: 0.9.8</summary>

## [0.9.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-network-security-v0.9.7...google-cloud-network-security-v0.9.8) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-network-services: 0.5.8</summary>

## [0.5.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-network-services-v0.5.7...google-cloud-network-services-v0.5.8) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-notebooks: 1.10.2</summary>

## [1.10.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-notebooks-v1.10.1...google-cloud-notebooks-v1.10.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-optimization: 1.8.2</summary>

## [1.8.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-optimization-v1.8.1...google-cloud-optimization-v1.8.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-orchestration-airflow: 1.12.0</summary>

## [1.12.0](https://github.com/googleapis/google-cloud-python/compare/google-cloud-orchestration-airflow-v1.11.1...google-cloud-orchestration-airflow-v1.12.0) (2024-02-15)


### Features

* Added field data_retention_config to EnvironmentConfig ([0268729](https://github.com/googleapis/google-cloud-python/commit/02687292d82cd4243d774ed26b5d072fe7e6c3ea))
* Added field storage_config to Environment ([0268729](https://github.com/googleapis/google-cloud-python/commit/02687292d82cd4243d774ed26b5d072fe7e6c3ea))
* Added field web_server_plugins_mode to SoftwareConfig ([0268729](https://github.com/googleapis/google-cloud-python/commit/02687292d82cd4243d774ed26b5d072fe7e6c3ea))
* Added ListWorkloads RPC ([0268729](https://github.com/googleapis/google-cloud-python/commit/02687292d82cd4243d774ed26b5d072fe7e6c3ea))


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-os-config: 1.17.2</summary>

## [1.17.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-os-config-v1.17.1...google-cloud-os-config-v1.17.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-os-login: 2.14.2</summary>

## [2.14.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-os-login-v2.14.1...google-cloud-os-login-v2.14.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-phishing-protection: 1.11.2</summary>

## [1.11.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-phishing-protection-v1.11.1...google-cloud-phishing-protection-v1.11.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-policy-troubleshooter: 1.11.2</summary>

## [1.11.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-policy-troubleshooter-v1.11.1...google-cloud-policy-troubleshooter-v1.11.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([7c2f2c2](https://github.com/googleapis/google-cloud-python/commit/7c2f2c29d74c9584efc42ddfe8bc098a594391a2))
</details>

<details><summary>google-cloud-policysimulator: 0.1.5</summary>

## [0.1.5](https://github.com/googleapis/google-cloud-python/compare/google-cloud-policysimulator-v0.1.4...google-cloud-policysimulator-v0.1.5) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-policytroubleshooter-iam: 0.1.4</summary>

## [0.1.4](https://github.com/googleapis/google-cloud-python/compare/google-cloud-policytroubleshooter-iam-v0.1.3...google-cloud-policytroubleshooter-iam-v0.1.4) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-private-ca: 1.10.2</summary>

## [1.10.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-private-ca-v1.10.1...google-cloud-private-ca-v1.10.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-private-catalog: 0.9.8</summary>

## [0.9.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-private-catalog-v0.9.7...google-cloud-private-catalog-v0.9.8) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-public-ca: 0.3.8</summary>

## [0.3.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-public-ca-v0.3.7...google-cloud-public-ca-v0.3.8) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-rapidmigrationassessment: 0.1.6</summary>

## [0.1.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-rapidmigrationassessment-v0.1.5...google-cloud-rapidmigrationassessment-v0.1.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-recaptcha-enterprise: 1.18.0</summary>

## [1.18.0](https://github.com/googleapis/google-cloud-python/compare/google-cloud-recaptcha-enterprise-v1.17.1...google-cloud-recaptcha-enterprise-v1.18.0) (2024-02-15)


### Features

* [google-cloud-recaptcha-enterprise] Add an API method for reordering firewall policies ([#12302](https://github.com/googleapis/google-cloud-python/issues/12302)) ([c48819c](https://github.com/googleapis/google-cloud-python/commit/c48819c7166f418fe450ec6f5abfc9c899c5bef8))


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-recommendations-ai: 0.10.9</summary>

## [0.10.9](https://github.com/googleapis/google-cloud-python/compare/google-cloud-recommendations-ai-v0.10.8...google-cloud-recommendations-ai-v0.10.9) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-recommender: 2.15.2</summary>

## [2.15.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-recommender-v2.15.1...google-cloud-recommender-v2.15.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12308](https://github.com/googleapis/google-cloud-python/issues/12308)) ([74dabeb](https://github.com/googleapis/google-cloud-python/commit/74dabebab206189e649ff6e00f3c7809d96c043b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-redis: 2.15.2</summary>

## [2.15.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-redis-v2.15.1...google-cloud-redis-v2.15.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-redis-cluster: 0.1.4</summary>

## [0.1.4](https://github.com/googleapis/google-cloud-python/compare/google-cloud-redis-cluster-v0.1.3...google-cloud-redis-cluster-v0.1.4) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-resource-manager: 1.12.2</summary>

## [1.12.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-resource-manager-v1.12.1...google-cloud-resource-manager-v1.12.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-resource-settings: 1.9.2</summary>

## [1.9.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-resource-settings-v1.9.1...google-cloud-resource-settings-v1.9.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-retail: 1.20.0</summary>

## [1.20.0](https://github.com/googleapis/google-cloud-python/compare/google-cloud-retail-v1.19.1...google-cloud-retail-v1.20.0) (2024-02-15)


### Features

* [google-cloud-retail] add analytics service ([#12294](https://github.com/googleapis/google-cloud-python/issues/12294)) ([8b5f319](https://github.com/googleapis/google-cloud-python/commit/8b5f319689a0b8ac4af3055b9705bfaf0706bd37))


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-run: 0.10.4</summary>

## [0.10.4](https://github.com/googleapis/google-cloud-python/compare/google-cloud-run-v0.10.3...google-cloud-run-v0.10.4) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-scheduler: 2.13.2</summary>

## [2.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-scheduler-v2.13.1...google-cloud-scheduler-v2.13.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-secret-manager: 2.18.2</summary>

## [2.18.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-secret-manager-v2.18.1...google-cloud-secret-manager-v2.18.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-securesourcemanager: 0.1.4</summary>

## [0.1.4](https://github.com/googleapis/google-cloud-python/compare/google-cloud-securesourcemanager-v0.1.3...google-cloud-securesourcemanager-v0.1.4) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-securitycenter: 1.27.0</summary>

## [1.27.0](https://github.com/googleapis/google-cloud-python/compare/google-cloud-securitycenter-v1.26.1...google-cloud-securitycenter-v1.27.0) (2024-02-15)


### Features

* [google-cloud-securitycenter] Add application field to finding's list of attributes ([#12301](https://github.com/googleapis/google-cloud-python/issues/12301)) ([c26abaf](https://github.com/googleapis/google-cloud-python/commit/c26abaf0206db382a6f8262f8cabddd87e6eed69))


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))
</details>

<details><summary>google-cloud-securitycentermanagement: 0.1.6</summary>

## [0.1.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-securitycentermanagement-v0.1.5...google-cloud-securitycentermanagement-v0.1.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([89c1b05](https://github.com/googleapis/google-cloud-python/commit/89c1b054f321b90ab4eed0139a3a2a79c369730d))


### Documentation

* [google-cloud-securitycentermanagement] Finish a sentence with a period ([#12300](https://github.com/googleapis/google-cloud-python/issues/12300)) ([833998a](https://github.com/googleapis/google-cloud-python/commit/833998a27193f6d9c95d054a352702439c596165))
</details>

<details><summary>google-cloud-service-control: 1.11.2</summary>

## [1.11.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-service-control-v1.11.1...google-cloud-service-control-v1.11.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
</details>

<details><summary>google-cloud-service-directory: 1.11.2</summary>

## [1.11.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-service-directory-v1.11.1...google-cloud-service-directory-v1.11.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-service-management: 1.8.2</summary>

## [1.8.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-service-management-v1.8.1...google-cloud-service-management-v1.8.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
</details>

<details><summary>google-cloud-service-usage: 1.10.2</summary>

## [1.10.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-service-usage-v1.10.1...google-cloud-service-usage-v1.10.2) (2024-02-15)


### Bug Fixes

* [Many APIs] fix `ValueError` in `test__validate_universe_domain` ([#12283](https://github.com/googleapis/google-cloud-python/issues/12283)) ([f20b41a](https://github.com/googleapis/google-cloud-python/commit/f20b41ac35b02a40135b83edfe819ff7a355ab21))
* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
</details>

<details><summary>google-cloud-servicehealth: 0.1.3</summary>

## [0.1.3](https://github.com/googleapis/google-cloud-python/compare/google-cloud-servicehealth-v0.1.2...google-cloud-servicehealth-v0.1.3) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-shell: 1.9.2</summary>

## [1.9.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-shell-v1.9.1...google-cloud-shell-v1.9.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-source-context: 1.5.2</summary>

## [1.5.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-source-context-v1.5.1...google-cloud-source-context-v1.5.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
</details>

<details><summary>google-cloud-speech: 2.24.2</summary>

## [2.24.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-speech-v2.24.1...google-cloud-speech-v2.24.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-storage-transfer: 1.11.2</summary>

## [1.11.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-storage-transfer-v1.11.1...google-cloud-storage-transfer-v1.11.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12309](https://github.com/googleapis/google-cloud-python/issues/12309)) ([c23398a](https://github.com/googleapis/google-cloud-python/commit/c23398a48d23d48e7f96971dd504ff184841666b))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-storageinsights: 0.1.7</summary>

## [0.1.7](https://github.com/googleapis/google-cloud-python/compare/google-cloud-storageinsights-v0.1.6...google-cloud-storageinsights-v0.1.7) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-support: 0.1.6</summary>

## [0.1.6](https://github.com/googleapis/google-cloud-python/compare/google-cloud-support-v0.1.5...google-cloud-support-v0.1.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-talent: 2.13.2</summary>

## [2.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-talent-v2.13.1...google-cloud-talent-v2.13.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-tasks: 2.16.2</summary>

## [2.16.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-tasks-v2.16.1...google-cloud-tasks-v2.16.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-telcoautomation: 0.2.2</summary>

## [0.2.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-telcoautomation-v0.2.1...google-cloud-telcoautomation-v0.2.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-texttospeech: 2.16.2</summary>

## [2.16.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-texttospeech-v2.16.1...google-cloud-texttospeech-v2.16.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-tpu: 1.18.2</summary>

## [1.18.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-tpu-v1.18.1...google-cloud-tpu-v1.18.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-trace: 1.13.2</summary>

## [1.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-trace-v1.13.1...google-cloud-trace-v1.13.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-translate: 3.15.2</summary>

## [3.15.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-translate-v3.15.1...google-cloud-translate-v3.15.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-video-live-stream: 1.7.2</summary>

## [1.7.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-video-live-stream-v1.7.1...google-cloud-video-live-stream-v1.7.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-video-stitcher: 0.7.8</summary>

## [0.7.8](https://github.com/googleapis/google-cloud-python/compare/google-cloud-video-stitcher-v0.7.7...google-cloud-video-stitcher-v0.7.8) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-video-transcoder: 1.12.2</summary>

## [1.12.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-video-transcoder-v1.12.1...google-cloud-video-transcoder-v1.12.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-videointelligence: 2.13.2</summary>

## [2.13.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-videointelligence-v2.13.1...google-cloud-videointelligence-v2.13.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-vision: 3.7.1</summary>

## [3.7.1](https://github.com/googleapis/google-cloud-python/compare/google-cloud-vision-v3.7.0...google-cloud-vision-v3.7.1) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([2451e88](https://github.com/googleapis/google-cloud-python/commit/2451e88f302bc582b3f6d01a6ec6aceba7646252))
</details>

<details><summary>google-cloud-vm-migration: 1.8.2</summary>

## [1.8.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-vm-migration-v1.8.1...google-cloud-vm-migration-v1.8.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-cloud-vmwareengine: 1.4.2</summary>

## [1.4.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-vmwareengine-v1.4.1...google-cloud-vmwareengine-v1.4.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-cloud-vpc-access: 1.10.2</summary>

## [1.10.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-vpc-access-v1.10.1...google-cloud-vpc-access-v1.10.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-cloud-webrisk: 1.14.2</summary>

## [1.14.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-webrisk-v1.14.1...google-cloud-webrisk-v1.14.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-cloud-websecurityscanner: 1.14.2</summary>

## [1.14.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-websecurityscanner-v1.14.1...google-cloud-websecurityscanner-v1.14.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-cloud-workflows: 1.14.2</summary>

## [1.14.2](https://github.com/googleapis/google-cloud-python/compare/google-cloud-workflows-v1.14.1...google-cloud-workflows-v1.14.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12310](https://github.com/googleapis/google-cloud-python/issues/12310)) ([41821da](https://github.com/googleapis/google-cloud-python/commit/41821da1fe08cc2aeeefc8c8f516023e4b0d0700))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-cloud-workstations: 0.5.5</summary>

## [0.5.5](https://github.com/googleapis/google-cloud-python/compare/google-cloud-workstations-v0.5.4...google-cloud-workstations-v0.5.5) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-geo-type: 0.3.6</summary>

## [0.3.6](https://github.com/googleapis/google-cloud-python/compare/google-geo-type-v0.3.5...google-geo-type-v0.3.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-maps-addressvalidation: 0.3.10</summary>

## [0.3.10](https://github.com/googleapis/google-cloud-python/compare/google-maps-addressvalidation-v0.3.9...google-maps-addressvalidation-v0.3.10) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-maps-fleetengine: 0.1.8</summary>

## [0.1.8](https://github.com/googleapis/google-cloud-python/compare/google-maps-fleetengine-v0.1.7...google-maps-fleetengine-v0.1.8) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-maps-fleetengine-delivery: 0.1.6</summary>

## [0.1.6](https://github.com/googleapis/google-cloud-python/compare/google-maps-fleetengine-delivery-v0.1.5...google-maps-fleetengine-delivery-v0.1.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-maps-mapsplatformdatasets: 0.3.6</summary>

## [0.3.6](https://github.com/googleapis/google-cloud-python/compare/google-maps-mapsplatformdatasets-v0.3.5...google-maps-mapsplatformdatasets-v0.3.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-maps-places: 0.1.9</summary>

## [0.1.9](https://github.com/googleapis/google-cloud-python/compare/google-maps-places-v0.1.8...google-maps-places-v0.1.9) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-maps-routing: 0.6.6</summary>

## [0.6.6](https://github.com/googleapis/google-cloud-python/compare/google-maps-routing-v0.6.5...google-maps-routing-v0.6.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-shopping-css: 0.1.3</summary>

## [0.1.3](https://github.com/googleapis/google-cloud-python/compare/google-shopping-css-v0.1.2...google-shopping-css-v0.1.3) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-shopping-merchant-inventories: 0.1.4</summary>

## [0.1.4](https://github.com/googleapis/google-cloud-python/compare/google-shopping-merchant-inventories-v0.1.3...google-shopping-merchant-inventories-v0.1.4) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-shopping-merchant-reports: 0.1.4</summary>

## [0.1.4](https://github.com/googleapis/google-cloud-python/compare/google-shopping-merchant-reports-v0.1.3...google-shopping-merchant-reports-v0.1.4) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>google-shopping-type: 0.1.3</summary>

## [0.1.3](https://github.com/googleapis/google-cloud-python/compare/google-shopping-type-v0.1.2...google-shopping-type-v0.1.3) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

<details><summary>grafeas: 1.9.2</summary>

## [1.9.2](https://github.com/googleapis/google-cloud-python/compare/grafeas-v1.9.1...grafeas-v1.9.2) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).