# Changelog

## [0.1.6](https://github.com/googleapis/google-cloud-python/compare/google-maps-fleetengine-delivery-v0.1.5...google-maps-fleetengine-delivery-v0.1.6) (2024-02-15)


### Bug Fixes

* **deps:** [Many APIs] Require `google-api-core&gt;=1.34.1` ([#12311](https://github.com/googleapis/google-cloud-python/issues/12311)) ([e4c864b](https://github.com/googleapis/google-cloud-python/commit/e4c864b3e67c7f7f33dfb0d2107fa138492ad338))
* fix ValueError in test__validate_universe_domain ([f3974d4](https://github.com/googleapis/google-cloud-python/commit/f3974d46a9ba9f549e31251ebc2daeb6b9b4745a))

## [0.1.5](https://github.com/googleapis/google-cloud-python/compare/google-maps-fleetengine-delivery-v0.1.4...google-maps-fleetengine-delivery-v0.1.5) (2024-02-06)


### Bug Fixes

* Add google-auth as a direct dependency ([d7d730a](https://github.com/googleapis/google-cloud-python/commit/d7d730acd3b1da86b996fa18c81272f1c9a00406))
* Add staticmethod decorator to `_get_client_cert_source` and `_get_api_endpoint` ([d7d730a](https://github.com/googleapis/google-cloud-python/commit/d7d730acd3b1da86b996fa18c81272f1c9a00406))
* Resolve AttributeError 'Credentials' object has no attribute 'universe_domain' ([d7d730a](https://github.com/googleapis/google-cloud-python/commit/d7d730acd3b1da86b996fa18c81272f1c9a00406))

## [0.1.4](https://github.com/googleapis/google-cloud-python/compare/google-maps-fleetengine-delivery-v0.1.3...google-maps-fleetengine-delivery-v0.1.4) (2024-02-01)


### Features

* Allow users to explicitly configure universe domain ([#12244](https://github.com/googleapis/google-cloud-python/issues/12244)) ([8d6b772](https://github.com/googleapis/google-cloud-python/commit/8d6b7729d93c1347529a3d34ed6266af55225578))

## [0.1.3](https://github.com/googleapis/google-cloud-python/compare/google-maps-fleetengine-delivery-v0.1.2...google-maps-fleetengine-delivery-v0.1.3) (2023-12-13)


### Features

* [google-maps-fleetengine-delivery] add trace_id to Fleet Engine headers ([#12120](https://github.com/googleapis/google-cloud-python/issues/12120)) ([94238c8](https://github.com/googleapis/google-cloud-python/commit/94238c863b1806cc50d65431c425ef90dbd6ced7))

## [0.1.2](https://github.com/googleapis/google-cloud-python/compare/google-maps-fleetengine-delivery-v0.1.1...google-maps-fleetengine-delivery-v0.1.2) (2023-12-07)


### Features

* Add support for python 3.12 ([f920d22](https://github.com/googleapis/google-cloud-python/commit/f920d22f59fbd31822252b9677416a6cd436eba2))
* Introduce compatibility with native namespace packages ([f920d22](https://github.com/googleapis/google-cloud-python/commit/f920d22f59fbd31822252b9677416a6cd436eba2))


### Bug Fixes

* Require proto-plus &gt;= 1.22.3 ([f920d22](https://github.com/googleapis/google-cloud-python/commit/f920d22f59fbd31822252b9677416a6cd436eba2))
* Use `retry_async` instead of `retry` in async client ([f920d22](https://github.com/googleapis/google-cloud-python/commit/f920d22f59fbd31822252b9677416a6cd436eba2))

## [0.1.1](https://github.com/googleapis/google-cloud-python/compare/google-maps-fleetengine-delivery-v0.1.0...google-maps-fleetengine-delivery-v0.1.1) (2023-11-02)


### Features

* add default sensors for RawLocation & SupplementalLocation ([#11934](https://github.com/googleapis/google-cloud-python/issues/11934)) ([c503005](https://github.com/googleapis/google-cloud-python/commit/c503005e2cfe25cc96625506991d60ade327e213))

## 0.1.0 (2023-10-19)


### Features

* add initial files for google.maps.fleetengine.delivery.v1 ([#11814](https://github.com/googleapis/google-cloud-python/issues/11814)) ([9b403f4](https://github.com/googleapis/google-cloud-python/commit/9b403f450daebc7ab92770446769e4fc547152ba))

## Changelog
